# Generated by Django 5.0.3 on 2024-03-12 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionparams',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='дата конца отправки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distributionparams',
            name='time_end',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='время конца отправки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='distributionparams',
            name='date',
            field=models.DateField(verbose_name='дата начала отправки'),
        ),
        migrations.AlterField(
            model_name='distributionparams',
            name='time',
            field=models.TimeField(verbose_name='время начала отправки'),
        ),
    ]
