# Generated by Django 4.2 on 2024-03-27 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='log',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.client', verbose_name='клиент рассылки'),
        ),
        migrations.AddField(
            model_name='log',
            name='mailing_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.mailingsettings', verbose_name='рассылка'),
        ),
    ]
